// Existing repository seed content. Used only with PORTFOLIO_DEMO=true.
export const demoGames = [
  {
    slug: 'realm-runners',
    title: 'Realm Runners',
    description:
      'A fast-paced pixel platformer with procedurally generated levels, wall-jumping mechanics, and a retro synthwave soundtrack. Race through crumbling castles and ancient forests.',
    tag: 'PLATFORMER',
    tech: 'Unity · C# · Pixel Art',
    year: '2025',
    emoji: '🏃',
    bgColor: '#4A7C2F',
    published: true,
    sortOrder: 0,
  },
  {
    slug: 'chronicle-of-embers',
    title: 'Chronicle of Embers',
    description:
      'A top-down action RPG featuring a branching narrative, hand-drawn pixel art, and a dynamic weather system that affects gameplay and story outcomes.',
    tag: 'RPG',
    tech: 'Unreal Engine · C++ · Blueprints',
    year: '2024',
    emoji: '⚔️',
    bgColor: '#8B2E1A',
    published: true,
    sortOrder: 1,
  },
  {
    slug: 'glyph-garden',
    title: 'Glyph Garden',
    description:
      'A meditative puzzle game where players arrange ancient runes to restore magical gardens. Features 120 hand-crafted levels with increasing complexity.',
    tag: 'PUZZLE',
    tech: 'Unity · C# · Shader Graph',
    year: '2024',
    emoji: '🧩',
    bgColor: '#C8860A',
    published: true,
    sortOrder: 2,
  },
  {
    slug: 'bastion-command',
    title: 'Bastion Command',
    description:
      'A real-time strategy game set in a medieval fantasy world. Build fortresses, command armies, and defend your realm against waves of darkness.',
    tag: 'STRATEGY',
    tech: 'Godot · GDScript · Multiplayer',
    year: '2023',
    emoji: '🏰',
    bgColor: '#3B2A1A',
    published: true,
    sortOrder: 3,
  },
];

export const demoOtherProjects = [
  {
    slug: 'frame-by-frame',
    title: 'Frame by Frame',
    description: 'A sample cinematic title and motion-design study exploring pacing, typography, and atmosphere across a short visual sequence.',
    tag: 'MOTION DESIGN',
    tech: 'After Effects · Blender · Sound Design',
    year: '2025',
    emoji: '🎞️',
    bgColor: '#B95563',
    published: true,
    sortOrder: 0,
    portfolioSection: 'OTHER',
    projectContext: 'ACADEMIC',
  },
  {
    slug: 'signal-noise',
    title: 'Signal / Noise',
    description: 'A sample interactive installation concept that turns live audience input into generative color, rhythm, and projected form.',
    tag: 'INTERACTIVE ART',
    tech: 'TouchDesigner · WebSockets · Projection',
    year: '2025',
    emoji: '〰️',
    bgColor: '#247B76',
    published: true,
    sortOrder: 1,
    portfolioSection: 'OTHER',
    projectContext: 'HACKATHON',
  },
  {
    slug: 'pocket-atlas',
    title: 'Pocket Atlas',
    description: 'A playful web atlas that turns places, memories, and tiny observations into an explorable visual journal.',
    tag: 'WEB EXPERIMENT',
    tech: 'Next.js · Mapbox · Illustration',
    year: '2025',
    emoji: '🗺️',
    bgColor: '#7668C9',
    published: true,
    sortOrder: 2,
    portfolioSection: 'OTHER',
    projectContext: 'PERSONAL',
  },
  {
    slug: 'quiet-cuts',
    title: 'Quiet Cuts',
    description: 'A short-film editing study built around silence, restrained camera movement, and small shifts in rhythm.',
    tag: 'SHORT FILM',
    tech: 'DaVinci Resolve · Premiere Pro · Sound Design',
    year: '2024',
    emoji: '🎬',
    bgColor: '#C57A42',
    published: true,
    sortOrder: 3,
    portfolioSection: 'OTHER',
    projectContext: 'ACADEMIC',
  },
  {
    slug: 'color-reactor',
    title: 'Color Reactor',
    description: 'A compact live-visual instrument that converts movement and audio input into responsive color fields.',
    tag: 'CREATIVE TOOL',
    tech: 'TouchDesigner · OSC · WebGL',
    year: '2024',
    emoji: '🎛️',
    bgColor: '#D65C72',
    published: true,
    sortOrder: 4,
    portfolioSection: 'OTHER',
    projectContext: 'HACKATHON',
  },
  {
    slug: 'studio-notes',
    title: 'Studio Notes',
    description: 'An evolving visual identity notebook collecting title treatments, interface studies, and motion sketches.',
    tag: 'VISUAL DESIGN',
    tech: 'Figma · Illustrator · After Effects',
    year: '2024',
    emoji: '✎',
    bgColor: '#438F83',
    published: true,
    sortOrder: 5,
    portfolioSection: 'OTHER',
    projectContext: 'PERSONAL',
  },];
